version: "3.8"

networks:
  mynet:

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:rw
    command: ["./script.sh"]
    depends_on:
      - db
    networks:
      - mynet
    restart: on-failure

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 30s
      retries: 20
      interval: 15s
      start_period: 60s

volumes:
  db_data: {}
